
[functions.make-server-ccb86954]
enabled = true
verify_jwt = false
import_map = "./functions/make-server-ccb86954/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/make-server-ccb86954/index.tsx"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/make-server-ccb86954/*.html" ]
